# Generated by Django 4.1.7 on 2023-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='yangiliklar.uz/image/image'),
        ),
    ]
