# Generated by Django 4.2.1 on 2023-05-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_news_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_time']},
        ),
    ]
