# Generated by Django 4.2.1 on 2023-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_alter_news_image_alter_viewcount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='media/media/'),
        ),
    ]
