# Generated by Django 4.2.1 on 2023-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0014_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='views_count',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
